export enum Origin {
	ENTERTAINER = 'Entertainer',
	URCHIN = 'Urchin',
	NOBLE = 'Noble',
	GUILD_ARTISAN = 'Guild Artisan',
	SAILOR = 'Sailor',
	SAGE = 'Sage',
	FOLK_HERO = 'Folk Hero',
	HERMIT = 'Hermit',
	PIRATE = 'Pirate',
	CRIMINAL = 'Criminal',
	ACOLYTE = 'Acolyte',
	SOLDIER = 'Soldier',
	OUTLANDER = 'Outlander',
	CHARLATAN = 'Charlatan',
}
