export enum DNDUserActionType {
	MOVE,
	MELEE_ATTACK_TARGETS_SELECTION,
	MELEE_ATTACK_HITS_CHECK,
	MELEE_ATTACK_APPLY_DAMAGE,
	RANGED_ATTACK_TARGETS_SELECTION,
	RANGED_ATTACK_HITS_CHECK,
	RANGED_ATTACK_APPLY_DAMAGE,
	TARGET_SELECTION,
	ROLL,
	HIT_ROLL,
	DAMAGE_ROLL,
	SAVING_THROW_ROLL,
}
