export enum LessonOneStep {
	LESSON_INTRODUCTION,
	LEVEL_EXPLANATION,
	CLASS_EXPLANATION,
	CLASS_SELECTION,
	RACE_EXPLANATION,
	RACE_SELECTION,
	ORIGIN_EXPLANATION,
	ORIGIN_SELECTION,
	MASTERY_EXPLANATION_1,
	MASTERY_EXPLANATION_2,
	MASTERY_SELECTION,
	END,
}
