export enum LogType {
	DICE_ROLLER_ROLL,
	WEAPON_DAMAGE_ROLL,
	SPELL_DAMAGE_ROLL,
	WEAPON_HIT_ROLL,
	SPELL_HIT_ROLL,
	TUTORIAL_SYSTEM_MESSAGE,
	CHARACTER_MELEE_ATTACK_START,
	CHARACTER_RANGED_ATTACK_START,
	CHARACTER_SPELL_CAST_START,
	CHARACTER_SAVING_THROW_CHECK,
}
