export enum DNDClass {
	BARD = 'Bard',
	BARBARIAN = 'Barbarian',
	CLERIC = 'Cleric',
	DRUID = 'Druid',
	FIGHTER = 'Fighter',
	MONK = 'Monk',
	PALADIN = 'Paladin',
	RANGER = 'Ranger',
	ROGUE = 'Rogue',
	SORCERER = 'Sorcerer',
	WARLOCK = 'Warlock',
	WIZARD = 'Wizard',
	ARTIFICER = 'Artificer',
}
